### ISSUE TITLE
Material Design is not work when build for android

### ISSUE THREAD

**Issue by nampdn** [driftyco/ionic2#671]
It can show the UI, but when I tap on the button, it doesn't have any water effect (ripple).

My environments:
Cordova CLI: 5.0.0
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Version: 2.0.0-alpha.37
Ionic CLI Version: 2.0.0-alpha.25
Ionic App Lib Version: 2.0.0-alpha.24
OS: Windows 8.1 (actually windows 10)
Node Version: v0.12.7

**Comment by mhartington** [comment]
What version of android are you deploying it to?

**Comment by nampdn** [comment]
It's android 4.2.2, added Crosswalk-lite

**Comment by adamdbradley** [comment]
Right now ripple isn't enabled for Android 4.4 and below, but if you have crosswalk it should be working. 

On the device running crosswalk lite, what's the value for `navigator.userAgent` and `navigator.platform`?

This is where it figures out if it should enable ripple or not:
https://github.com/driftyco/ionic2/blob/master/ionic/platform/registry.ts#L51

**Comment by nampdn** [comment]
Thanks.
But I think ripple is a great modern UI feature, why don't we turn it on for all supported version of android? Is there any limited about old android browser?

**Comment by mlynch** [comment]
@nampdn Android L introduced Material Design, and is only supported on a subset of modern devices. We plan to support material design on those devices only.

Is this a device that runs Android L?

**Comment by nampdn** [comment]
I know Ionic design should be fit for each platform and version we have. But I think if we bring `md` for old android device (4.0+), then the user would happy.
By the way, I try to use crosswalk (not lite version). It still don't have the ripple effect which I really like it.
My device is not run Android L.

**Comment by adamdbradley** [comment]
On the device running crosswalk, within the browser, what's the value for `navigator.userAgent` and `navigator.platform`?

**Comment by adamdbradley** [comment]
You could get those values by putting this somewhere in your index.html file, and copying the output in your browsers console. Thanks

```
<script>
console.log(navigator.userAgent);
console.log(navigator.platform);
</script>
```

**Comment by nampdn** [comment]
Hi,
I have trace the value of those variable.
```
navigator.userAgent = Mozilla/5.0 (Linux; Android 4.2.2; Lenovo A680_ROW Build/JDQ39) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Cros
swalk/15.44.384.13 Mobile Safari/537.36
navigator.platform = Linux armv7l
```

**Comment by adamdbradley** [comment]
Oh cool, it looks like it's keeping `Android 4.2` in there, but adds `Chrome` and `Crosswalk`. I'll update the logic to check for Chrome too. Thanks for the help!

**Comment by nampdn** [comment]
Hope it help ionic2 more better. But I think it should have a `config` function to enable ripple if we want to (not rely on android version).

**Comment by adamdbradley** [comment]
This is a config: http://ionicframework.com/docs/v2/nightly/api/config/Config/

You'r app.js file could try something like:

```@App({
  template: `<ion-nav [root]="root"></ion-nav>`
  config: {
    tabbarPlacement: ...,
    platforms: {
     android: {
       activator: 'ripple'
     }
    }
  }
})```

This is the default: https://github.com/driftyco/ionic2/blob/master/ionic/platform/registry.ts#L51

**Comment by nampdn** [comment]
Great! Thanks for your help.
